name: PR annoy-o-bot

on:
  workflow_dispatch:


jobs:
  annotate-pr:
    runs-on: ubuntu-latest
    name: Get open pull requests
    steps:
      - name: Get PR
        uses: RbnBosshard/PR-metadata-action@main
        with:
          token_github: ${{ secrets.GITHUB_TOKEN }}
          token_gitlab: ${{ secrets.GITLAB_TOKEN }}
          webhook_value: ${{ secrets.WEBHOOK }}
