name: PR annoy-o-bot

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  annotate-pr:
    runs-on: ubuntu-latest
    name: Get open pull requests
    steps:
      - name: Get PR
        uses: RbnBosshard/PR-metadata-action@main
        with:
          token_github: ${{ secrets.GITHUB_TOKEN }}
          token_gitlab: ${{ secrets.NODEJS }}
          webhook_value: ${{ secrets.WEBHOOK }}