name: PR annoy-o-bot

on:
  schedule:
    - cron: '44 8 * * 1-5'
    - cron: "*/2 * * * *"

jobs:
  annotate-pr:
    runs-on: ubuntu-latest
    name: Get open pull requests
    steps:
      - name: Get PR
        uses: RbnBosshard/PR-metadata-action@main
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token_github: ${{ secrets.GITHUB_TOKEN }}
          token_gitlab: ${{ secrets.GITLAB_TOKEN }}
          webhook_value: ${{ secrets.WEBHOOK }}